<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Fun_CPU</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ppy.SDL2-CS" Version="1.0.82" />
      <PackageReference Include="sdl2.v140.redist" Version="2.0.4" />
    </ItemGroup>

    <ItemGroup>
      <None Include="rom.bin" CopyToOutputDirectory="PreserveNewest" Condition="Exists('rom.bin')" />
    </ItemGroup>

    <Target Name="BuildRom" BeforeTargets="Build" Condition="!Exists('rom.bin')">
      <Exec Command="python &quot;$(ProjectDir)Assembly\basicassembler.py&quot; &quot;$(ProjectDir)Assembly\clogs&quot; &quot;$(ProjectDir)rom.bin&quot;" />
    </Target>

    <Import Project="SdlNativeCopy.targets" />

</Project>
